my_diffbot: 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
  right_wheel_controller:
    type: effort_controllers/JointVelocityController 
    joint: right_wheel_joint
    pid: {p: 5.0, i: 15, d: 0 } 
  left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 5.0, i: 15, d: 0 }